# Generated by Django 5.1.7 on 2025-04-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigyasa', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_signout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
